// `bdk export agents` on an in-memory store: the adapter definitions, the
// Claude Code rendering, writes, `--check` drift and the handler's flags.
import { describe, expect, it } from "vitest";

import commands from "../../../../schema/cli/commands.json" with { type: "json" };
import { createRegistry, loadIndex } from "../../shared/registry/index.ts";
import type { Refusal } from "../../shared/refusal/index.ts";
import { memoryStore } from "../../shared/store/index.ts";
import { ADAPTERS } from "../domain/adapters.ts";
import { adapterFile, HOSTS } from "../domain/hosts.ts";
import { exportRegistrations } from "../index.ts";
import { renderAgents } from "../render/agents.ts";
import { exportAgents } from "../use-cases/agents.ts";
import type { AgentsReport } from "../domain/report.ts";

const PLUGIN = "/plugins/bdk";
const ROOT = "/work/repo";
const NAMES = ["worker", "reader", "reviewer", "runner", "scout"];

function generated(): Record<string, string> {
  return Object.fromEntries(
    ADAPTERS.map((adapter) => [
      `${PLUGIN}/agents/${adapter.name}.md`,
      adapterFile(adapter, HOSTS.claude),
    ]),
  );
}

describe("adapter definitions", () => {
  it("define exactly the five adapters in a fixed order", () => {
    expect(ADAPTERS.map((adapter) => adapter.name)).toEqual(NAMES);
  });

  it("map to the Claude Code tools and models of role-contracts, Adapters", () => {
    const rows = ADAPTERS.map((adapter) => ({
      name: adapter.name,
      tools: adapter.tools.flatMap((tool) => HOSTS.claude.tools[tool]),
      model: HOSTS.claude.models[adapter.tier],
    }));
    expect(rows).toEqual([
      {
        name: "worker",
        tools: ["Read", "Edit", "Write", "Bash", "Grep", "Glob", "SendMessage"],
        model: "sonnet",
      },
      {
        name: "reader",
        tools: ["Read", "Grep", "Glob", "Bash", "SendMessage"],
        model: "opus",
      },
      {
        name: "reviewer",
        tools: ["Read", "Grep", "Glob", "Bash", "SendMessage"],
        model: "sonnet",
      },
      { name: "runner", tools: ["Read", "Bash", "SendMessage"], model: "haiku" },
      { name: "scout", tools: ["Read", "Grep", "Glob", "Bash", "SendMessage"], model: "haiku" },
    ]);
  });

  it("give only the worker a file-writing tool", () => {
    const writers = ADAPTERS.filter((adapter) => adapter.tools.includes("edit"));
    expect(writers.map((adapter) => adapter.name)).toEqual(["worker"]);
  });

  it("keep every description within the 250-character listing budget", () => {
    for (const adapter of ADAPTERS) expect(adapter.description.length).toBeLessThanOrEqual(250);
  });
});

describe("adapterFile", () => {
  it("renders frontmatter with the generated marker and a one-sentence body", () => {
    const [worker] = ADAPTERS;
    if (worker === undefined) throw new Error("no adapters");
    const text = adapterFile(worker, HOSTS.claude);
    expect(text).toBe(
      [
        "---",
        "# Generated by `bdk export agents --host claude`; do not edit.",
        "name: worker",
        `description: ${worker.description}`,
        "model: sonnet",
        "tools:",
        "  - Read",
        "  - Edit",
        "  - Write",
        "  - Bash",
        "  - Grep",
        "  - Glob",
        "  - SendMessage",
        "---",
        "",
        worker.sentence,
        "",
      ].join("\n"),
    );
  });

  it("ends every body with one sentence and no carriage return", () => {
    for (const adapter of ADAPTERS) {
      const text = adapterFile(adapter, HOSTS.claude);
      const body = text.split("---\n\n")[1] ?? "";
      expect(body.trim().split(/(?<=\.)\s/)).toHaveLength(1);
      expect(body.trim().endsWith(".")).toBe(true);
      expect(text).not.toContain("\r");
    }
  });
});

describe("exportAgents", () => {
  it("writes the five adapter files and reports them as changed", () => {
    const store = memoryStore();
    const report = exportAgents(
      { store, pluginRoot: PLUGIN },
      { host: "claude", check: false, root: ROOT },
    ) as AgentsReport;
    expect(report.changed).toBe(true);
    expect(report.files.map((file) => file.adapter)).toEqual(NAMES);
    expect(report.files[0]).toEqual({
      adapter: "worker",
      path: "../../plugins/bdk/agents/worker.md",
      changed: true,
    });
    for (const [path, content] of Object.entries(generated())) {
      expect(store.read(path)).toBe(content);
    }
  });

  it("reports nothing changed on a second run and names paths relative to the root", () => {
    const store = memoryStore(generated());
    const report = exportAgents(
      { store, pluginRoot: ROOT },
      { host: "claude", check: false, root: ROOT, out: `${PLUGIN}/agents` },
    ) as AgentsReport;
    expect(report.changed).toBe(false);
    expect(report.files.every((file) => !file.changed)).toBe(true);
  });

  it("uses --out and leaves every other file in it alone", () => {
    const store = memoryStore({ [`${ROOT}/out/implementer.md`]: "v2 agent\n" });
    const report = exportAgents(
      { store, pluginRoot: PLUGIN },
      { host: "claude", check: false, root: ROOT, out: `${ROOT}/out` },
    ) as AgentsReport;
    expect(report.files.map((file) => file.path)).toEqual(NAMES.map((name) => `out/${name}.md`));
    expect(store.read(`${ROOT}/out/implementer.md`)).toBe("v2 agent\n");
  });

  it("--check passes on committed files and writes nothing", () => {
    const store = memoryStore(generated());
    const report = exportAgents(
      { store, pluginRoot: PLUGIN },
      { host: "claude", check: true, root: PLUGIN },
    ) as AgentsReport;
    expect(report).toEqual({
      host: "claude",
      files: NAMES.map((name) => ({ adapter: name, path: `agents/${name}.md`, changed: false })),
      changed: false,
    });
  });

  it("--check refuses a hand edit and a missing file with policy/generated-drift", () => {
    const reader = `${PLUGIN}/agents/reader.md`;
    const files = Object.entries(generated()).filter(([path]) => !path.endsWith("/scout.md"));
    const store = memoryStore(
      Object.fromEntries(
        files.map(([path, content]) => [path, path === reader ? `${content}edited\n` : content]),
      ),
    );
    const refusal = exportAgents(
      { store, pluginRoot: PLUGIN },
      { host: "claude", check: true, root: PLUGIN },
    ) as Refusal;
    expect(refusal).toMatchObject({
      rule: "policy/generated-drift",
      why: "2 generated adapter files differ from bdk export agents --host claude: agents/reader.md (edited), agents/scout.md (missing)",
      instead: ["bdk export agents --host claude"],
    });
    expect(store.read(`${PLUGIN}/agents/scout.md`)).toBeUndefined();
  });
});

describe("renderAgents", () => {
  it("lists one line per adapter file and a summary", () => {
    const report: AgentsReport = {
      host: "claude",
      files: [
        { adapter: "worker", path: "agents/worker.md", changed: true },
        { adapter: "reader", path: "agents/reader.md", changed: false },
      ],
      changed: true,
    };
    expect(renderAgents(report)).toBe(
      "written    agents/worker.md\nunchanged  agents/reader.md\nclaude: 1 of 2 adapter files changed\n",
    );
  });
});

describe("export agents handler", () => {
  async function run(argv: string[], files: Record<string, string> = {}) {
    const store = memoryStore(files);
    const registry = createRegistry(
      loadIndex(commands),
      exportRegistrations({ store, pluginRoot: PLUGIN }),
    );
    let stdout = "";
    const code = await registry.run({
      argv,
      cwd: `${ROOT}/src`,
      runtime: {
        nodeVersion: "24.21.0",
        env: {},
        platform: "linux",
        home: "/home/dev",
        workTree: () => ROOT,
        which: () => undefined,
        readStdin: () => "",
      },
      streams: { stdout: (text) => (stdout += text), stderr: () => undefined },
    });
    return { code, stdout, store };
  }

  it("refuses a missing --host with input/missing-argument", async () => {
    const result = await run(["export", "agents", "--json"]);
    expect(result.code).toBe(3);
    expect(JSON.parse(result.stdout)).toMatchObject({
      rule: "input/missing-argument",
      why: "--host is required: claude is the only host in 3.0",
      instead: ["bdk export agents --host claude", "bdk export agents --help"],
    });
  });

  it("refuses another host with input/invalid-argument", async () => {
    const result = await run(["export", "agents", "--host", "gemini", "--json"]);
    expect(result.code).toBe(3);
    expect(JSON.parse(result.stdout)).toMatchObject({ rule: "input/invalid-argument" });
  });

  it("resolves a relative --out against the working directory", async () => {
    const result = await run(["export", "agents", "--host", "claude", "--out", "gen", "--json"]);
    expect(result.code).toBe(0);
    expect(JSON.parse(result.stdout)).toMatchObject({
      files: expect.arrayContaining([
        { adapter: "worker", path: "src/gen/worker.md", changed: true },
      ]) as unknown,
    });
    expect(result.store.exists(`${ROOT}/src/gen/worker.md`)).toBe(true);
  });

  it("exits 2 on drift under --check", async () => {
    const result = await run(["export", "agents", "--host", "claude", "--check"]);
    expect(result.code).toBe(2);
    expect(result.stdout).toContain("policy/generated-drift");
  });

  it("prints the text rendering without --json", async () => {
    const result = await run(["export", "agents", "--host", "claude"]);
    expect(result.stdout).toContain("claude: 5 of 5 adapter files changed");
  });
});
