// Per-host tool maps and model tiers for the adapters (design T23-D21 of
// v3-t23a-roles-adapters): Claude Code is the only host in 3.0, because a map
// no live host verified would be guesswork. A host added here needs its value
// in the `--host` flag of `schema/cli/commands.json`.
import type { AdapterDefinition, Tier, ToolClass } from "./adapters.ts";

export interface HostMap {
  readonly id: string;
  readonly tools: Readonly<Record<ToolClass, readonly string[]>>;
  readonly models: Readonly<Record<Tier, string>>;
  /** The tiers whose model takes an `effort` level; the others get no `effort` key. */
  readonly effortTiers: readonly Tier[];
}

export const HOSTS = {
  claude: {
    id: "claude",
    tools: {
      read: ["Read"],
      search: ["Grep", "Glob"],
      edit: ["Edit", "Write"],
      shell: ["Bash"],
      message: ["SendMessage"],
    },
    models: { fast: "haiku", balanced: "sonnet", deep: "opus" },
    // Haiku runs without the frontmatter's effort level (HOST-FACTS `model-override`).
    effortTiers: ["balanced", "deep"],
  },
} as const satisfies Readonly<Record<string, HostMap>>;

export type HostId = keyof typeof HOSTS;

/** The adapter file for a host. Byte-stable: LF, fixed key order, no timestamp (`kernel-cli/export`). */
export function adapterFile(adapter: AdapterDefinition, host: HostMap): string {
  const tools = [
    ...adapter.tools.flatMap((tool) => host.tools[tool]),
    ...(adapter.starts === undefined ? [] : [`Agent(${adapter.starts.join(", ")})`]),
  ];
  return [
    "---",
    `# Generated by \`bdk export agents --host ${host.id}\`; do not edit.`,
    `name: ${adapter.name}`,
    `description: ${adapter.description}`,
    `model: ${host.models[adapter.tier]}`,
    ...(host.effortTiers.includes(adapter.tier) ? [`effort: ${adapter.effort}`] : []),
    "tools:",
    ...tools.map((tool) => `  - ${tool}`),
    "---",
    "",
    adapter.sentence,
    "",
  ].join("\n");
}
