// Generates `schema/cli/output/rules-{check,explain,prune,import,export,stats,accept}.json`
// (kernel/scripts/export-schemas.ts).
import * as z from "zod";

import { ROLES, RULE_ID } from "../../shared/vocabulary/index.ts";
import type {
  AcceptReport,
  CheckReport,
  ExplainReport,
  ExportReport,
  ImportReport,
  PruneItem,
  StatsReport,
} from "../domain/report.ts";

const ruleId = z.string().regex(RULE_ID);
const count = z.int().min(0);
const relativePath = z.string().min(1).meta({ description: "Relative to the project root." });
const globs = z.array(z.string().min(1));
const CHANGE = "2026-09-25-passwordless-login";

export const rulesCheckOutput = z
  .strictObject({
    valid: z.literal(true),
    rules: count.meta({ description: "Rule files checked, tombstones included." }),
    bundle: count,
    project: count,
    tombstones: count,
  })
  .meta({
    title: "bdk rules check --json",
    description:
      "Check the rule files of the bundle and the project: ids, the frontmatter, knowledge sources, tombstones and rules.disabled.",
    examples: [{ valid: true, rules: 87, bundle: 81, project: 6, tombstones: 1 }],
  }) satisfies z.ZodType<CheckReport>;

export const rulesExplainOutput = z
  .strictObject({
    file: relativePath,
    role: z.enum(ROLES),
    rules: z
      .array(
        z.strictObject({
          id: ruleId,
          matchedBy: z
            .string()
            .nullable()
            .meta({ description: "The glob that matched the file; null for a global rule." }),
          kind: z.enum(["house", "knowledge"]),
          beyondCap: z
            .boolean()
            .meta({ description: "True when the rule falls beyond rules.max-per-package." }),
        }),
      )
      .meta({ description: "The selection in package order, without the cap." }),
    disabled: z.array(ruleId).meta({
      description: "Rules the role would read for the file that rules.disabled switches off.",
    }),
  })
  .meta({
    title: "bdk rules explain --json",
    description: "Which rules apply to a file for a role, and why.",
    examples: [
      {
        file: "src/api/login.ts",
        role: "reviewer",
        rules: [
          { id: "BDK-CQ-1", matchedBy: null, kind: "house", beyondCap: false },
          { id: "API-1", matchedBy: "src/api/**", kind: "house", beyondCap: false },
        ],
        disabled: ["BDK-SEC-3"],
      },
    ],
  }) satisfies z.ZodType<ExplainReport>;

export const rulesPruneOutput = z
  .strictObject({
    items: z.array(
      z.strictObject({
        id: ruleId,
        reason: z.enum(["no-match", "uncited"]),
        detail: z.string().min(1),
      }),
    ),
    total: count,
    truncated: z.boolean(),
  })
  .meta({
    title: "bdk rules prune --json",
    description:
      "List rules whose globs match no file or that no entry of the last N Changes cites.",
    examples: [
      {
        items: [
          { id: "API-3", reason: "no-match", detail: 'applies: ["legacy/**"] matches 0 files' },
        ],
        total: 1,
        truncated: false,
      },
    ],
  }) satisfies z.ZodType<{ items: readonly PruneItem[] }>;

export const rulesImportOutput = z
  .strictObject({
    imported: z.array(
      z.strictObject({
        from: relativePath,
        rules: z.array(ruleId).min(1),
        applies: globs
          .optional()
          .meta({ description: "The file's `paths:`; absent: global rules." }),
      }),
    ),
    skipped: z.array(z.strictObject({ from: relativePath, why: z.string().min(1) })),
    dryRun: z.boolean().meta({ description: "True with --dry-run: nothing was written." }),
    projection: z
      .array(relativePath)
      .meta({ description: "The projection files the import rewrote or deleted." }),
  })
  .meta({
    title: "bdk rules import --json",
    description:
      "Import a project's `.claude/rules/*.md` into `.bdk/rules/`, one rule per top-level bullet, applies from paths.",
    examples: [
      {
        imported: [
          {
            from: ".claude/rules/api-style.md",
            rules: ["API-STYLE-1", "API-STYLE-2"],
            applies: ["src/api/**"],
          },
        ],
        skipped: [{ from: ".claude/rules/bdk-generated.md", why: "generated by rules export" }],
        dryRun: false,
        projection: [".claude/rules/bdk-generated-scoped.md"],
      },
    ],
  }) satisfies z.ZodType<ImportReport>;

export const rulesExportOutput = z
  .strictObject({
    files: z.array(
      z.strictObject({
        path: relativePath,
        rules: count,
        paths: globs.optional().meta({
          description: "The scoped file's `paths:`: the sorted union of its rules' applies.",
        }),
        changed: z.boolean().meta({
          description: "True when the file was (or, with --check, would be) rewritten or deleted.",
        }),
      }),
    ),
  })
  .meta({
    title: "bdk rules export --json",
    description:
      "Generate the host projection of the project's rules: `.claude/rules/bdk-generated.md` and `bdk-generated-scoped.md`.",
    examples: [
      {
        files: [
          { path: ".claude/rules/bdk-generated.md", rules: 4, changed: false },
          {
            path: ".claude/rules/bdk-generated-scoped.md",
            rules: 2,
            paths: ["src/api/**", "web/**/*.tsx"],
            changed: true,
          },
        ],
      },
    ],
  }) satisfies z.ZodType<ExportReport>;

const auditItem = z.strictObject({
  id: z.string().min(1).meta({
    description:
      "`<changeId>/<entry id>` for an entry, `<changeId>/<ticket>` for an attempt finding.",
  }),
  source: z.enum(["entry", "attempt"]),
  type: z.string().min(1),
  summary: z.string().min(1),
  refs: z.array(z.string()),
  applies: globs.optional(),
  evidence: z.array(z.string()).optional(),
  at: z.iso.datetime({ precision: 3 }),
  adopted: z
    .boolean()
    .meta({ description: "True when a rule's origin or evidence names the item." }),
});

export const rulesStatsOutput = z
  .strictObject({
    minChanges: z.int().min(1),
    recurring: z
      .array(
        z.strictObject({
          fingerprint: z.string().min(1),
          summary: z.string().min(1),
          changes: z
            .int()
            .min(1)
            .meta({ description: "Distinct Changes the fingerprint appears in." }),
          occurrences: z.int().min(1),
          changeIds: z.array(z.string().min(1)),
        }),
      )
      .meta({
        description:
          "Fingerprints of learning entries and attempt findings seen in at least minChanges distinct Changes.",
      }),
    entries: z
      .strictObject({ items: z.array(auditItem), total: count, truncated: z.boolean() })
      .optional()
      .meta({
        description:
          "With --entries: every learning, finding and blocker entry and every attempt finding, newest first.",
      }),
    citations: z
      .array(z.strictObject({ id: ruleId, entries: count, changes: count }))
      .meta({ description: "Entries naming each rule id in refs, rules never cited included." }),
  })
  .meta({
    title: "bdk rules stats --json",
    description:
      "The audit view: recurring items across Changes, the raw findings and learnings, and citations by rule id.",
    examples: [
      {
        minChanges: 3,
        recurring: [
          {
            fingerprint: `sha256:${"9f2c".repeat(16)}`,
            summary: "scoped test run missed the negative case",
            changes: 3,
            occurrences: 5,
            changeIds: [CHANGE, "2026-09-27-export-csv", "2026-09-29-audit-log"],
          },
        ],
        citations: [{ id: "BDK-CQ-4", entries: 12, changes: 4 }],
      },
    ],
  }) satisfies z.ZodType<StatsReport>;

export const rulesAcceptOutput = z
  .strictObject({
    id: ruleId,
    path: relativePath,
    origin: z.string().min(1),
    projection: z
      .array(relativePath)
      .meta({ description: "The projection files the adoption rewrote." }),
  })
  .meta({
    title: "bdk rules accept --json",
    description:
      "Adopt a rule: write `.bdk/rules/<PREFIX>-<n>.md` from the user's decision and regenerate the projection.",
    examples: [
      {
        id: "ARCHP-1",
        path: ".bdk/rules/ARCHP-1.md",
        origin: `${CHANGE}/L-m2x9v7qa`,
        projection: [".claude/rules/bdk-generated-scoped.md"],
      },
    ],
  }) satisfies z.ZodType<AcceptReport>;
