// The host projection of the project's rules (`kernel-cli/rules`, bdk rules
// export; design D-7 of v3-t31): the global rules in one file without
// `paths:`, the scoped ones in a second file whose `paths:` is the sorted
// union of their `applies`. The BDK pack is never projected.
import type { LoadedRule } from "./rule.ts";

const PROJECTION_GLOBAL = ".claude/rules/bdk-generated.md";
const PROJECTION_SCOPED = ".claude/rules/bdk-generated-scoped.md";

const MARKER =
  "<!-- Generated by `bdk rules export --claude` from .bdk/rules/. Do not edit: change the rule files and rerun it. -->";

export interface ProjectionFile {
  /** Relative to the project root. */
  readonly path: string;
  readonly rules: number;
  /** The scoped file's `paths:`; absent for the global file. */
  readonly paths?: readonly string[];
  /** The file's text; undefined when it holds no rule and must not exist. */
  readonly content: string | undefined;
}

/** `- [<id>] <text>`, continuation lines indented, ` (applies: ...)` after a scoped rule. */
export function ruleLine(rule: Pick<LoadedRule, "id" | "text" | "applies">): string {
  const applies =
    rule.applies === undefined || rule.applies.length === 0
      ? ""
      : ` (applies: ${rule.applies.join(", ")})`;
  return `- [${rule.id}] ${rule.text.replace(/\n/g, "\n  ")}${applies}\n`;
}

/** The two projection files of the enabled, non-tombstone project rules, in id order. */
export function projectionFiles(rules: readonly LoadedRule[]): [ProjectionFile, ProjectionFile] {
  const scoped = rules.filter((rule) => (rule.applies?.length ?? 0) > 0);
  const global = rules.filter((rule) => (rule.applies?.length ?? 0) === 0);
  const paths = [...new Set(scoped.flatMap((rule) => rule.applies ?? []))].sort();
  const body = (list: readonly LoadedRule[]): string => list.map(ruleLine).join("");
  const frontmatter = `---\npaths:\n${paths.map((path) => `  - ${JSON.stringify(path)}\n`).join("")}---\n`;
  return [
    {
      path: PROJECTION_GLOBAL,
      rules: global.length,
      content: global.length === 0 ? undefined : `${MARKER}\n\n${body(global)}`,
    },
    {
      path: PROJECTION_SCOPED,
      rules: scoped.length,
      paths,
      content: scoped.length === 0 ? undefined : `${frontmatter}${MARKER}\n\n${body(scoped)}`,
    },
  ];
}

/** True for a projection file name, which `rules import` and `doctor` skip. */
export function isProjection(name: string): boolean {
  return /^bdk-generated(?:-[a-z]+)?\.md$/.test(name);
}
