// Renders the Reference pages from the source model (v3-268-docs-site-user-docs, design D4).
// Output is deterministic: the same sources give the same bytes, so the drift test can compare.

import { Document, isMap, isScalar, isSeq } from "yaml";

import type { SettingDoc } from "../../plugins/bdk/src/config/domain/describe.ts";
import type { Rule } from "../../plugins/bdk/src/rules/domain/rule.ts";
import { commandHelp, globalHelp, groupHelp } from "../../plugins/bdk/src/shared/cli/help.ts";
import type { AgentDoc, HookDoc, Model, PluginDoc, SkillDoc } from "./model.ts";

/** The plugin whose Reference is split into pages: it alone has a CLI and settings. */
const SPLIT = "bdk";

function header(sources: string): string {
  return `<!-- Generated by \`pnpm docs:reference\` from ${sources}. Do not edit: change the sources and run it again. -->\n\n`;
}

/** Escapes HTML outside code spans; markdown and code spans stay as written. */
function prose(value: string): string {
  return value
    .split(/(`+[^`]*`+)/)
    .map((part, i) =>
      i % 2 === 1
        ? part
        : part.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;"),
    )
    .join("");
}

function code(value: string): string {
  const fence = value.includes("`") ? "``" : "`";
  return `${fence}${fence === "``" ? ` ${value} ` : value}${fence}`;
}

function page(sources: string, title: string, body: readonly string[]): string {
  return `${header(sources)}# ${title}\n\n::: v-pre\n\n${body.join("\n\n")}\n\n:::\n`;
}

const STARTED_BY: Record<SkillDoc["invocation"], string> = {
  "user-and-model": "Started by: you, or Claude when your request matches the description below.",
  internal: "Started by: other BDK skills only. It is not in the `/` menu.",
  "user-only": "Started by: you only. Claude does not start it on its own.",
};

function skillEntry(plugin: string, skill: SkillDoc, level: string): string {
  const call = `/${plugin}:${skill.name}`;
  return [
    `${level} ${code(call)} {#${skill.name}}`,
    code(skill.argumentHint === undefined ? call : `${call} ${skill.argumentHint}`),
    STARTED_BY[skill.invocation],
    prose(skill.description),
  ].join("\n\n");
}

function agentEntry(agent: AgentDoc, level: string): string {
  const facts = [
    `Model: ${agent.model === undefined ? "the session's model" : code(agent.model)}`,
    ...(agent.tools === undefined ? [] : [`Tools: ${agent.tools.map(code).join(", ")}`]),
  ].join(" · ");
  return [`${level} ${code(agent.name)} {#${agent.name}}`, facts, prose(agent.description)].join(
    "\n\n",
  );
}

function kebab(value: string): string {
  return value
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/[^A-Za-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
}

function hookAnchor(hook: HookDoc, all: readonly HookDoc[]): string {
  const same = all.filter((other) => other.event === hook.event && other.matcher === hook.matcher);
  const base = kebab(hook.matcher === undefined ? hook.event : `${hook.event} ${hook.matcher}`);
  return same.length > 1 ? `${base}-${same.indexOf(hook) + 1}` : base;
}

function hookEntry(hook: HookDoc, all: readonly HookDoc[], level: string): string {
  const title = hook.matcher === undefined ? hook.event : `${hook.event} on ${hook.matcher}`;
  const facts = [
    `Event: ${code(hook.event)}`,
    ...(hook.matcher === undefined ? [] : [`Matcher: ${code(hook.matcher)}`]),
    ...(hook.timeout === undefined ? [] : [`Timeout: ${hook.timeout} s`]),
  ].join(" · ");
  return [
    `${level} ${title} {#${hookAnchor(hook, all)}}`,
    facts,
    prose(hook.description),
    `Runs: ${code(hook.command)}`,
  ].join("\n\n");
}

export function settingAnchor(key: string): string {
  return kebab(key.replaceAll("<", "").replaceAll(">", ""));
}

function settingType(doc: SettingDoc): string {
  switch (doc.type) {
    case "mapping":
      return "mapping of the keys below";
    case "items":
      return "list of items, each with an `id`; layers merge items by `id`";
    case "list":
      return `list of ${doc.of ?? "string"}s`;
    case "map":
      return "mapping of names to values";
    case "enum":
      return `one of ${(doc.values ?? []).map(code).join(", ")}`;
    case "integer":
      return doc.max !== undefined
        ? `integer, ${doc.min ?? "any"} to ${doc.max}`
        : doc.min !== undefined
          ? `integer, at least ${doc.min}`
          : "integer";
    case "string":
    case "boolean":
      return doc.type;
  }
}

function settingFacts(doc: SettingDoc): string[] {
  return [
    ...(doc.required ? ["Required"] : []),
    ...(doc.default === undefined ? [] : [`Default: ${code(JSON.stringify(doc.default))}`]),
  ];
}

/** A key under an item (`<id>`) or a record value (`<role>`): shown in its parent's table. */
function isMember(doc: SettingDoc): boolean {
  return doc.key.includes("<");
}

function cell(value: string): string {
  return value.replaceAll("|", "\\|");
}

function settingEntry(doc: SettingDoc, all: readonly SettingDoc[]): string {
  const level = doc.key.includes(".") ? "###" : "##";
  const members = all.filter((other) => isMember(other) && other.key.startsWith(`${doc.key}.`));
  // A record's direct value (`models.<role>`) is listed only by its parent; a member nested
  // deeper is listed by the nearest parent that is not a member itself.
  const own = members.filter(
    (member) =>
      !all.some(
        (other) =>
          other !== doc &&
          !isMember(other) &&
          member.key.startsWith(`${other.key}.`) &&
          other.key.startsWith(`${doc.key}.`),
      ),
  );
  const table =
    own.length === 0
      ? []
      : [
          "| Key | Type | Required or default | Description |\n|---|---|---|---|\n" +
            own
              .map(
                (member) =>
                  `| ${code(member.key.slice(doc.key.length + 1))} | ${cell(settingType(member))} | ${cell(settingFacts(member).join(", "))} | ${cell(prose(member.description))} |`,
              )
              .join("\n"),
        ];
  return [
    `${level} ${code(doc.key)} {#${settingAnchor(doc.key)}}`,
    [`Type: ${settingType(doc)}`, ...settingFacts(doc)].join(" · "),
    prose(doc.description),
    ...table,
    ...(level === "##" ? [sectionExample(doc, all)] : []),
  ].join("\n\n");
}

/** A rule's title: its leading bold phrase (`**Naming.**`), else its first sentence. */
function ruleTitle(rule: Rule): string {
  const bold = /^\*\*(.+?)\*\*/.exec(rule.text)?.[1];
  const title = bold ?? /^[^.]*/.exec(rule.text)?.[0] ?? rule.id;
  return title.replace(/[.:]$/, "");
}

/** The group a pack rule belongs to, from its directory: `code-quality`, `languages/react`. */
function ruleGroup(rule: Rule): string {
  if (rule.language !== null) return `Language pack: ${rule.language}`;
  const dir = /rules\/([^/]+)\//.exec(rule.file)?.[1] ?? "other";
  const words = dir.replaceAll("-", " ");
  return words.charAt(0).toUpperCase() + words.slice(1);
}

function cellText(value: string): string {
  return prose(value).replaceAll("|", "\\|");
}

function rulesPage(rules: readonly Rule[]): string {
  const groups = [...new Set(rules.map(ruleGroup))];
  const table = [
    "| Rule | Title | Files | Stages |",
    "|---|---|---|---|",
    ...rules.map(
      (rule) =>
        `| [${code(rule.id)}](#${kebab(rule.id)}) | ${cellText(ruleTitle(rule))} | ${rule.paths.map(code).join(", ")} | ${rule.stages.join(", ")} |`,
    ),
  ].join("\n");
  const entries = groups.flatMap((group) => [
    `## ${group}`,
    ...rules
      .filter((rule) => ruleGroup(rule) === group)
      .map((rule) => {
        const facts = [
          `Kind: ${rule.kind}`,
          ...(rule.language === null ? [] : [`Language pack: ${code(rule.language)}`]),
          `Stages: ${rule.stages.map(code).join(", ")}`,
          `Files: ${rule.paths.map(code).join(", ")}`,
          ...(rule.source === null ? [] : [`Source: <${rule.source}>`]),
          ...(rule.verified === null ? [] : [`Verified: ${rule.verified}`]),
        ].join(" · ");
        return [`### ${code(rule.id)} {#${kebab(rule.id)}}`, facts, prose(rule.text)].join("\n\n");
      }),
  ]);
  return page(
    "plugins/bdk/rules/**/*.md",
    "bdk rules - the rule pack that the roles of each stage read",
    [
      "The rules BDK ships. `bdk rules for` gives each role the rules of its stage that match the files it works on; a language pack's rules apply only when `languages` lists the pack. Switch a rule off with `enabled: false` under its id in `rules`, narrow its `paths` or `stages` there, and declare your own rules in the same map: see [Rules](/concepts/rules).",
      table,
      ...entries,
    ],
  );
}

/** A key's description cut to one line for a YAML comment: up to its first "; " or sentence. */
function shortDescription(description: string): string {
  const clause = description.split("; ")[0] ?? description;
  if (clause !== description) return clause;
  return /^.*?\.(?=\s|$)/.exec(description)?.[0] ?? description;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** `over` laid onto `base`: mappings merge key by key, any other value replaces. */
function overlay(base: unknown, over: unknown): unknown {
  if (!isPlainObject(base) || !isPlainObject(over)) return over;
  const merged: Record<string, unknown> = { ...base };
  for (const [key, value] of Object.entries(over)) merged[key] = overlay(base[key], value);
  return merged;
}

/** The comment of a key in a section example: its short description, enum values, its default. */
function keyComment(doc: SettingDoc, value: unknown): string {
  const scalar = (fallback: unknown) =>
    fallback !== undefined && !isPlainObject(fallback) && !Array.isArray(fallback);
  const facts = [
    ...(doc.type === "enum" ? [(doc.values ?? []).join(" | ")] : []),
    ...(scalar(doc.default) && value !== doc.default ? [`default: ${String(doc.default)}`] : []),
  ];
  const short = shortDescription(doc.description).replace(/\.$/, "");
  return ` ${short}${facts.length === 0 ? "" : ` (${facts.join(", ")})`}`;
}

/**
 * One top-level section whole: its example laid over every key's default, each key with its
 * description as a comment; the section's own description stands above the block, and a comment
 * already shown in the block is not repeated.
 */
function sectionExample(section: SettingDoc, all: readonly SettingDoc[]): string {
  const byKey = new Map(all.map((doc) => [doc.key, doc]));
  const defaults: Record<string, unknown> = {};
  for (const doc of all) {
    if (doc.key.includes("<") || !`${doc.key}.`.startsWith(`${section.key}.`)) continue;
    const path = doc.key.split(".");
    let at = defaults;
    for (const segment of path.slice(0, -1)) at = at[segment] as Record<string, unknown>;
    at[path.at(-1) ?? ""] = doc.type === "mapping" ? {} : doc.default;
  }
  const value = (section.examples ?? []).reduce<unknown>(
    (merged, example) => overlay(merged, { [section.key]: example }),
    defaults,
  );
  const document = new Document(value);
  const shown = new Set<string>([keyComment(section, undefined)]);
  // The key of a member of `prefix`: an item of a list or an entry of a record (`models.<role>`).
  const memberKey = (prefix: string): string | undefined => {
    const member = all.find((doc) => doc.key.startsWith(`${prefix}.<`));
    return member && `${prefix}.${member.key.slice(prefix.length + 1).split(".")[0] ?? ""}`;
  };
  const childKey = (prefix: string, name: string): string | undefined => {
    const own = prefix === "" ? name : `${prefix}.${name}`;
    return byKey.has(own) ? own : memberKey(prefix);
  };
  const visit = (node: unknown, prefix: string): void => {
    if (isSeq(node)) {
      const item = memberKey(prefix);
      if (item !== undefined) for (const entry of node.items) visit(entry, item);
      return;
    }
    if (!isMap(node)) return;
    for (const pair of node.items) {
      if (!isScalar(pair.key)) continue;
      const key = childKey(prefix, String(pair.key.value));
      if (key === undefined) continue;
      const doc = byKey.get(key);
      const comment = doc && keyComment(doc, isScalar(pair.value) ? pair.value.value : undefined);
      if (comment !== undefined && !shown.has(comment)) {
        pair.key.commentBefore = comment;
        shown.add(comment);
      }
      visit(pair.value, key);
    }
  };
  visit(document.contents, "");
  return `\`\`\`yaml\n${document.toString()}\`\`\``;
}

/** The problems of `bdk plan check`, each with what it means and what to do. */
function planProblems(model: Model): string[] {
  return [
    "#### Problems {#plan-check-problems}",
    "Each line under `problems:` starts with the kind of the problem (`check` in `--json`), then the part ids it concerns and a message. The kinds, in the order the command lists them:",
    [
      "| Problem | What it means | What to do |",
      "|---|---|---|",
      ...model.planProblems.map(
        (problem) =>
          `| ${code(problem.check)} | ${cellText(problem.meaning)} | ${cellText(problem.fix)} |`,
      ),
    ].join("\n"),
  ];
}

/** Sections a command entry of the CLI page carries below its help, by command path. */
const COMMAND_SECTIONS: Readonly<Record<string, (model: Model) => string[]>> = {
  "plan check": planProblems,
};

function splitPages(plugin: PluginDoc, model: Model): [string, string][] {
  const dir = `plugins/${plugin.name}`;
  return [
    [
      `${plugin.name}/skills.md`,
      page(
        `${dir}/skills/*/SKILL.md`,
        `${plugin.name} skills - every skill of the ${plugin.name} plugin`,
        [
          prose(plugin.description),
          ...plugin.skills.map((skill) => skillEntry(plugin.name, skill, "##")),
        ],
      ),
    ],
    [
      `${plugin.name}/agents.md`,
      page(`${dir}/agents/*.md`, `${plugin.name} agents - the subagents its skills start`, [
        "The skills of the plugin start these agents; you do not start them yourself.",
        ...plugin.agents.map((agent) => agentEntry(agent, "##")),
      ]),
    ],
    [
      `${plugin.name}/hooks.md`,
      page(`${dir}/hooks/hooks.json`, `${plugin.name} hooks - what runs on Claude Code events`, [
        "Claude Code runs these hooks while the plugin is enabled.",
        ...plugin.hooks.map((hook) => hookEntry(hook, plugin.hooks, "##")),
      ]),
    ],
    [
      `${plugin.name}/cli.md`,
      page(
        `the command declarations of ${dir}/src/*/`,
        `${plugin.name} CLI - every command of the ${code("bdk")} command line`,
        [
          "The plugin ships the `bdk` command line; its skills run it. Each block is what the command prints with `--help`.",
          `\`\`\`text\n${globalHelp(model.cli)}\`\`\``,
          ...model.cli.flatMap((group) => [
            `## ${code(`bdk ${group.name}`)} {#${group.name}}`,
            `\`\`\`text\n${groupHelp(group)}\`\`\``,
            ...group.commands.map((command) => {
              const path =
                command.verb === undefined ? group.name : `${group.name} ${command.verb}`;
              return [
                `### ${code(`bdk ${path}`)} {#${kebab(path)}}`,
                `\`\`\`text\n${commandHelp(path, command)}\`\`\``,
                ...(COMMAND_SECTIONS[path]?.(model) ?? []),
              ].join("\n\n");
            }),
          ]),
        ],
      ),
    ],
    [`${plugin.name}/rules.md`, rulesPage(model.rules)],
    [
      `${plugin.name}/settings.md`,
      page(
        `the settings schema in ${dir}/src/config/domain/settings.ts`,
        `${plugin.name} settings - every key of .bdk/settings.yaml`,
        [
          "Keys are written in YAML in `.bdk/settings.yaml` (shared with the team), `.bdk/settings.local.yaml` (yours, not committed) or `~/.config/bdk/settings.yaml` (all your projects; `$XDG_CONFIG_HOME/bdk/settings.yaml` when that variable is set). `<id>` stands for the `id` of an item; `<role>` and `<orchestrator>` for a name you choose.",
          "Each section shows itself whole: an example with every key of the section, what the key is for, and its default where the example changes it. A settings file needs only the keys you change.",
          ...model.settings
            .filter((doc) => !isMember(doc))
            .map((doc) => settingEntry(doc, model.settings)),
        ],
      ),
    ],
  ];
}

function singlePage(plugin: PluginDoc): [string, string] {
  const dir = `plugins/${plugin.name}`;
  const body = [
    prose(plugin.description),
    ...(plugin.skills.length === 0
      ? []
      : ["## Skills", ...plugin.skills.map((skill) => skillEntry(plugin.name, skill, "###"))]),
    ...(plugin.agents.length === 0
      ? []
      : ["## Agents", ...plugin.agents.map((agent) => agentEntry(agent, "###"))]),
    ...(plugin.hooks.length === 0
      ? []
      : ["## Hooks", ...plugin.hooks.map((hook) => hookEntry(hook, plugin.hooks, "###"))]),
  ];
  return [`${plugin.name}.md`, page(`${dir}/`, `${plugin.name} - the ${plugin.name} plugin`, body)];
}

/** Every generated Reference page, by its path under `docs/reference/`. */
export function renderReference(model: Model): Map<string, string> {
  return new Map(
    model.plugins.flatMap((plugin) =>
      plugin.name === SPLIT ? splitPages(plugin, model) : [singlePage(plugin)],
    ),
  );
}
