export { fileStore, findProjectRoot, memoryStore } from "./store.ts";
export type { Store } from "./store.ts";
export { splitFrontmatter } from "./frontmatter.ts";
export { INDEX_SCHEMA_VERSION, openIndex } from "./index-db.ts";
export type { IndexDb } from "./index-db.ts";
export { migrateDocument, readDocument, writeDocument } from "./state/documents.ts";
export type { KindOverrides, MigrationResult, StateDocument } from "./state/documents.ts";
export { ENTRY_TYPES } from "./state/entry.ts";
export type { EntryType } from "./state/entry.ts";
export { findingFingerprint, learningFingerprint } from "./state/fingerprint.ts";
export { generateDesignIndex, generatePlanIndex } from "./state/indexes.ts";
export { STATE_KINDS } from "./state/registry.ts";
export type { KindName } from "./state/registry.ts";
